name = "lastfm"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-04-08"

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
