name: Fetch scrobble count

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Next.js endpoint
      run: |
        curl --request GET \
          --url https://hakke.ro/api/last.fm/scrobble \
          --header 'Authorization: ${{ secrets.SCRAPE_AUTHORIZATION }}'
